services:

    sentence.service:
        class: YarnyardBundle\Service\SentenceService
        arguments:
            - '@doctrine.orm.entity_manager'

    sentence.repository:
        class: YarnyardBundle\Entity\SentenceRepository
        factory: [ '@doctrine.orm.entity_manager' , 'getRepository' ]
        arguments:
            -   YarnyardBundle\Entity\Sentence
