YarnyardBundle\Entity\Review:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        rating:
            type: integer
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        createdBy:
            targetEntity: YarnyardBundle\Entity\User
            gedmo:
                blameable:
                    on: create
        updatedBy:
            targetEntity: YarnyardBundle\Entity\User
            gedmo:
                blameable:
                    on: update
        story:
            targetEntity: YarnyardBundle\Entity\Story