YarnyardBundle\Entity\Story:
    type: entity
    repositoryClass: YarnyardBundle\Entity\StoryRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
        completed:
            type: boolean
        random:
            type: boolean
        numSentences:
            type: integer
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        createdBy:
            targetEntity: YarnyardBundle\Entity\User
            gedmo:
                blameable:
                    on: create
        updatedBy:
            targetEntity: YarnyardBundle\Entity\User
            gedmo:
                blameable:
                    on: update
