YarnyardBundle\Entity\User:
    type: entity
    repositoryClass: YarnyardBundle\Entity\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: true
            unique: true
        uuid:
            type: string
            length: 24
            nullable: false
            unique: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update