YarnyardBundle\Entity\User:
    type: entity
    repositoryClass: YarnyardBundle\Entity\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        uuid:
            type: string
            length: 24
            nullable: false
            unique: true
        createdAt:
            type: datetime
            nullable: true
        updatedAt:
            type: datetime
            nullable: true