imports:
    - { resource: user/services.yml }
    - { resource: story/services.yml }

services:

    query_string_rebuilder:
        class: YarnyardBundle\Util\Request\QueryStringRebuilder

    pagination_header.generator:
        class: YarnyardBundle\Util\Pagination\PaginationHeaderGenerator
        arguments:
            - '@query_string_rebuilder'

    date_time.normalizer:
        class: YarnyardBundle\Serializer\Normalizer\DateTimeNormalizer
        tags:
            -  { name: serializer.normalizer }

    elasticsearch_query_modifier:
        class: YarnyardBundle\Service\ElasticsearchQueryModifier
        arguments:
            - '@fos_elastica.index.app'
