imports:
    - { resource: user/services.yml }
    - { resource: story/services.yml }
    - { resource: sentence/services.yml }
    - { resource: participant/services.yml }

services:

    query_string_rebuilder:
        class: YarnyardBundle\Util\Request\QueryStringRebuilder

    pagination_header.generator:
        class: YarnyardBundle\Util\Pagination\PaginationHeaderGenerator
        arguments:
            - '@query_string_rebuilder'

    date_time.normalizer:
        class: YarnyardBundle\Serializer\Normalizer\DateTimeNormalizer
        tags:
            -  { name: serializer.normalizer }

    date_interval_counter:
        class: YarnyardBundle\Util\DateInterval\IntervalCounter

    elasticsearch_query_modifier:
        class: YarnyardBundle\Service\ElasticsearchQueryModifier
        arguments:
            - '@fos_elastica.index.app'

    query_builder.param_converter:
        class: YarnyardBundle\Request\ParamConverter\QueryBuilderParamConverter
        arguments:
            - '@mickadoo_search.entity_finder'
            - '@elasticsearch_query_modifier'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: request.param_converter, converter: query_builder.param_converter }

    rabbit:
        class: YarnyardBundle\Util\RabbitMQ\Connection
        arguments:
            - '%rabbit_mq_host%'
            - '%rabbit_mq_port%'
            - '%rabbit_mq_uname%'
            - '%rabbit_mq_pass%'
