imports:
    - { resource: user/services.yml }

services:

    query_string_rebuilder:
        class: YarnyardBundle\Util\Request\QueryStringRebuilder

    pagination_header.generator:
        class: YarnyardBundle\Util\Pagination\PaginationHeaderGenerator
        arguments:
            - '@query_string_rebuilder'