imports:
    - { resource: user/services.yml }
    - { resource: story/services.yml }
    - { resource: sentence/services.yml }

services:

    query_string_rebuilder:
        class: YarnyardBundle\Util\Request\QueryStringRebuilder

    pagination_header.generator:
        class: YarnyardBundle\Util\Pagination\PaginationHeaderGenerator
        arguments:
            - '@query_string_rebuilder'

    date_time.normalizer:
        class: YarnyardBundle\Serializer\Normalizer\DateTimeNormalizer
        tags:
            -  { name: serializer.normalizer }

    elasticsearch_query_modifier:
        class: YarnyardBundle\Service\ElasticsearchQueryModifier
        arguments:
            - '@fos_elastica.index.app'

    query_builder.param_converter:
        class: YarnyardBundle\Request\ParamConverter\QueryBuilderParamConverter
        arguments:
            - '@mickadoo_search.entity_finder'
            - '@elasticsearch_query_modifier'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: request.param_converter, converter: query_builder.param_converter }
