
getUserAction:
  description: 'Get a user'
  section: 'user'
  requirements:
    -
      name: 'id'
      dataType: 'int'
      requirement: '\d+'
      description: 'The user id'

getAllUsersAction:
  description: 'Get all users'
  section: 'user'

postStoryAction:
  description: 'Create a story'
  section: 'story'
  requirements:
    -
      name: 'title'
      dataType: 'string'
      requirement: '\w+'
      description: 'The title of the story'