
getUserAction:
    description: 'Get a user'
    section: 'user'
    requirements:
        -
            name: 'id'
            dataType: 'int'
            requirement: '\d+'
            description: 'The user id'

getAllUsersAction:
    resourceDescription: YarnyardBundle\Entity\User
    description: 'Get all users'
    section: 'user'

postStoryAction:
    description: 'Create a story'
    section: 'story'
    requirements:
        -
            name: 'title'
            dataType: 'string'
            description: 'The title of the story'
        -
            name: 'random'
            dataType: 'boolean'
            description: >
                You invite the contributors yourself OR have them randomly
                selected
        -
            name: 'rounds'
            dataType: 'integer'
            description: >
                End story after each contributor writes this number of
                sentences. If rounds is set to 0 then the story continues
                until the owner finishes it
            
getStoriesAction:
    resourceDescription: YarnyardBundle\Entity\Story
    description: 'Get all stories'
    section: 'story'
    parameters:
        -
            name: 'search'
            dataType: 'string'
            description: 'string to search for'
            required: false
        -
            name: 'contributorId'
            dataType: 'integer'
            description: 'limit to stories by a certain contributor'
            required: false
        -
            name: 'granteeId'
            dataType: 'integer'
            description: 'limit to stories a certain user can contribute to'
            required: false

postSentenceAction:
    description: 'Add a sentence to a story'
    section: 'sentence'
    requirements:
        -
            name: 'text'
            dataType: 'string'
            description: 'The sentence content'
        -
            name: 'storyId'
            dataType: 'integer'
            description: 'which story to append the sentence to'
