imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: en

framework:
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    serializer:
        enabled: true
        enable_annotations: true

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_migrations:
    dir_name: %kernel.root_dir%/migrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    body_converter:
        enabled: true
    format_listener: true
    routing_loader:
        include_format: false
        default_format: json
    view:
        view_response_listener: true
        formats:
            xml: false
            json : true
        default_engine: none
    access_denied_listener:
        json: true
    allowed_methods_listener: true

jwt_auth:
    client_id:     '%oauth_client_id%'
    client_secret: '%oauth_client_secret%'

fos_elastica:
    clients:
        default: { host: '%elastic.host%', port: 9200 }
    serializer: ~
    indexes:
        app:
            types:
                story:
                    serializer:
                        groups: [elastica]
                    persistence:
                        model: YarnyardBundle\Entity\Story
stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            blameable: true
