mickadoo_yarnyard_auth:
    resource: "@MickadooYarnyardAuthBundle/Resources/config/routing.yml"
    prefix:   /

mickadoo_yarnyard_user:
    resource: "@MickadooYarnyardUserBundle/Resources/config/routing.yml"
    prefix:   /

nelmio_api_doc_bundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc