mickadoo_yarnyard_api_doc_yaml_annotation:
    resource: "@MickadooYarnyardApiDocYamlAnnotationBundle/Resources/config/routing.yml"
    prefix:   /

mickadoo_yarnyard_user:
    resource: "@MickadooYarnyardUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

yarnyard_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: MickadooYarnyardApplicationBundle:Security:login }

yarnyard_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: MickadooYarnyardApplicationBundle:Security:loginCheck }

nelmio_api_doc_bundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc