security:
    encoders:
        Mickadoo\Yarnyard\Bundle\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 15

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_provider:
            id: yarnyard.user.user.provider

    firewalls:
        api_docs:
            pattern:   ^/api/doc
            security:  false
        create_user:
            pattern: ^/users$
            methods: [POST]
            security: false
        confirm_email:
            pattern: ^/confirm-email$
            security:  false
        default:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: jwt_auth.jwt_authenticator

    access_control:
        # You can omit this if /api can be accessed both authenticated and anonymously
        - { path: ^/, roles: [ IS_AUTHENTICATED_FULLY ] , methods: [POST, PUT, PATCH, DELETE]}
