security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 15

    providers:
        user_provider:
            id: 'user.provider'

    firewalls:
        api_docs:
            pattern:   ^/api/doc
            security:  false
        default:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: jwt_auth.jwt_authenticator

    access_control:
        -
            path: ^/
            allow_if: "!user.isAnonymous()"
            methods: [POST, PUT, PATCH, DELETE]
