# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  mickadoo_yarnyard_user.user.provider:
    class: Mickadoo\Yarnyard\Bundle\UserBundle\Entity\UserProvider
    arguments:
      - @mickadoo_yarnyard_user.user.repository
