services:
    kernel.listener.mickadoo_exception_handler:
        class: Mickadoo\Yarnyard\Library\ExceptionHandler\ExceptionHandler
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    yarnyard.library.validator.abstract_validator:
        abstract:  true
        arguments: ["@service_container"]

    mickadoo.yarnyard.library.serializer.scalar_normalizer:
        class: Mickadoo\Yarnyard\Library\Serializer\ScalarNormalizer
        tags:
            - { name: serializer.normalizer }