# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    kernel.listener.mickadoo_exception_handler:
        class: Mickadoo\Yarnyard\Library\ExceptionHandler\ExceptionHandler
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    yarnyard.library.validator.abstract_validator:
        abstract:  true
        arguments: ["@service_container"]
#            - [setContainer, ["@service_container"]]

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
