services:

    exception.code_mapping:
        class: YarnyardBundle\Exception\Mapping\ExceptionCodeMapper

    yarnyard.exception_handler:
        class: YarnyardBundle\Exception\Handler\ExceptionHandler
        tags:
            -
                name: kernel.event_listener
                event: kernel.exception
                method: onKernelException
        arguments:
            - '@translator'
            - '@exception.code_mapping'
            - '@array_decorator'

    array_decorator:
        class: YarnyardBundle\Util\ArrayDecorator
