services:

    yarnyard.auth.confirmation_token.repository:
        class: Mickadoo\Yarnyard\Bundle\AuthBundle\Entity\ConfirmationTokenRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Mickadoo\Yarnyard\Bundle\AuthBundle\Entity\ConfirmationToken

    confirmation_token.service:
        class: Mickadoo\Yarnyard\Bundle\AuthBundle\Service\ConfirmationTokenService
        arguments:
            - @yarnyard.user.user.repository
            - @yarnyard.auth.confirmation_token.repository
            - @yarnyard.user.role.repository