services:

    user.repository:
        class: YarnyardBundle\Entity\UserRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - YarnyardBundle\Entity\User

    user.provider:
        class: YarnyardBundle\Service\UserProvider
        arguments:
            - '@user.repository'
            - '@user.creator'

    user.manager:
        class: Doctrine\ORM\EntityManager
        factory: [ '@doctrine', 'getManagerForClass' ]
        arguments:
            - 'YarnyardBundle\Entity\User'

    user.creator:
        class: YarnyardBundle\Service\UserCreator
        arguments:
            - '@doctrine.orm.entity_manager'
