services:

    story.service:
        class: YarnyardBundle\Service\StoryCreator
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@validator'

    story.repository:
        class: YarnyardBundle\Entity\StoryRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - YarnyardBundle\Entity\Story
