services:

    story.creator:
        class: YarnyardBundle\Service\StoryCreator
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@validator'

    story.repository:
        class: YarnyardBundle\Entity\StoryRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - YarnyardBundle\Entity\Story

    story_completion.service:
        class: YarnyardBundle\Service\StoryCompletionService
        arguments:
            - '@sentence.repository'
            - '@doctrine.orm.entity_manager'
