services:

    story.service:
        class: YarnyardBundle\Service\StoryService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@validator'

    story.repository:
        class: YarnyardBundle\Entity\StoryRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - YarnyardBundle\Entity\Story

    participant_limit_calculator:
        class: YarnyardBundle\Service\ParticipantLimitCalculator
