user.controller:
    type: rest
    resource: "@YarnyardBundle/Controller/UserController.php"

story.controller:
    type: rest
    resource: "@YarnyardBundle/Controller/StoryController.php"

sentence.controller:
    type: rest
    resource: "@YarnyardBundle/Controller/SentenceController.php"
