services:

    ##### manager ######

    user.manager:
        class: Doctrine\ORM\EntityManager
        factory: [ '@doctrine', 'getManagerForClass' ]
        arguments:
            - YarnyardBundle\Entity\User

    ##### entity repository ######

    user.repository:
        class: YarnyardBundle\Entity\UserRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - YarnyardBundle\Entity\User

    role.repository:
        class: YarnyardBundle\Entity\RoleRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - YarnyardBundle\Entity\Role

    ##### provider ######

    user.provider:
        class: YarnyardBundle\Entity\UserProvider
        arguments:
            - '@user.repository'
            - '@user.service'

    ##### validator ######

    ##### param converter ######

    ##### entity services ######
    user.service:
        class: YarnyardBundle\Service\UserService
        arguments:
            - '@user.repository'
