Mickadoo\Yarnyard\Bundle\BaseDataBundle\Entity\Test:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      length: 32