Mickadoo\Yarnyard\Bundle\UserBundle\Entity\Role:
    type: entity
    repositoryClass:
        Mickadoo\Yarnyard\Bundle\UserBundle\Entity\RoleRepository
    id:
        role:
            type: integer
        user:
            associationKey: true
    manyToOne:
        user:
            targetEntity: User
            inversedBy: roles