Mickadoo\Yarnyard\Bundle\UserBundle\Entity\User:
  type: entity
  repositoryClass:
    Mickadoo\Yarnyard\Bundle\UserBundle\Entity\UserRepository
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    username:
      type: string
      length: 16
      nullable: false
    email:
      type: string
      length: 255
      nullable: true
    createdAt:
      type: datetime
      nullable: true
    updatedAt:
      type: datetime
      nullable: true
  oneToMany:
    roles:
      targetEntity: Role
      mappedBy: user