<?php

namespace Mickadoo\Yarnyard\Bundle\UserBundle\ConstantsInterface;

use Mickadoo\Yarnyard\Library\ErrorConstants\ErrorConstantsInterface;

interface UserErrorConstantsInterface extends ErrorConstantsInterface
{

    const ERROR_USER_NOT_SET = 'ERROR_USER_NOT_SET';
    const ERR_REQUEST_NOT_SET = 'ERR_REQUEST_NOT_SET';

    const ERROR_USER_EMAIL_CONTAINS_NON_ASCII = 'ERROR_USER_EMAIL_CONTAINS_NON_ASCII';
    const ERROR_USER_EMAIL_NOT_SET = 'ERROR_USER_EMAIL_NOT_SET';
    const ERROR_USER_EMAIL_INVALID = 'ERROR_USER_EMAIL_INVALID';
    const ERROR_USER_EMAIL_ALREADY_EXISTS = 'ERROR_USER_EMAIL_ALREADY_EXISTS';

    const ERROR_USER_USERNAME_NOT_SET = 'ERROR_USER_USERNAME_NOT_SET';
    const ERROR_USER_USERNAME_TOO_SHORT = 'ERROR_USER_USERNAME_TOO_SHORT';
    const ERROR_USER_USERNAME_TOO_LONG = 'ERROR_USER_USERNAME_TOO_LONG';
    const ERROR_USER_USERNAME_CONTAINS_NON_ASCII = 'ERROR_USER_USERNAME_CONTAINS_NON_ASCII';
    const ERROR_USER_USERNAME_ALREADY_EXISTS = 'ERROR_USER_USERNAME_ALREADY_EXISTS';
    
    const ERROR_USER_PASSWORD_NOT_SET = 'ERROR_USER_PASSWORD_NOT_SET';
    const ERROR_USER_PASSWORD_TOO_SHORT = 'ERROR_USER_PASSWORD_TOO_SHORT';
    const ERROR_USER_PASSWORD_TOO_LONG = 'ERROR_USER_PASSWORD_TOO_LONG';
    const ERROR_USER_PASSWORD_CONTAINS_NON_ASCII = 'ERROR_USER_PASSWORD_CONTAINS_NON_ASCII';
    

}