services:
    participant.sorter:
        class: YarnyardBundle\Service\ParticipantSorter
        arguments:
            - '@participation_grant.repository'

    participant_limit_calculator:
        class: YarnyardBundle\Service\ParticipantLimitCalculator

    participation_grant.repository:
        class: YarnyardBundle\Entity\ParticipationGrantRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - YarnyardBundle\Entity\ParticipationGrant

    next_participant_fetcher:
        class: YarnyardBundle\Service\NextParticipantFetcher
        arguments:
            - '@participant.sorter'
            - '@sentence.repository'
            - '@date_interval_counter'
