services:
    participant.sorter:
        class: YarnyardBundle\Service\ParticipantSorter
        arguments:
            - '@participation_grant.repository'

    participant_limit_calculator:
        class: YarnyardBundle\Service\ParticipantLimitCalculator

    participation_grant.repository:
        class: YarnyardBundle\Entity\ParticipationGrantRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - YarnyardBundle\Entity\ParticipationGrant

    turn_tracker:
        class: YarnyardBundle\Service\TurnTracker
        arguments:
            - '@participant.sorter'
            - '@sentence.repository'
            - '@date_interval_counter'

    random_participant_finder:
        class: YarnyardBundle\Service\RandomParticipantFinder
        arguments:
            - '@user.repository'
            - '@participation_grant.repository'
